apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: block-ephemeral-containers
spec:
  validationActions: 
    - Deny
  webhookConfiguration:
    timeoutSeconds: 30
  # evaluation:
  #   background:
  #     enabled: true
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
  validations:
  # even if use this fails 
  #  - expression: "!has(object.spec.ephemeralContainers)"
   - expression: >-
      object.spec.?ephemeralContainers.orValue([]).size() == 0
     message: "Ephemeral (debug) containers are not permitted."

