apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: require-run-as-non-root-user
  annotations:
    pod-policies.kyverno.io/autogen-controllers: deployments,cronjobs 
    policies.kyverno.io/title: Require Run As Non-Root User in ValidatingPolicy
    policies.kyverno.io/category: Pod Security Standards (Restricted) in ValidatingPolicy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.14.0
    kyverno.io/kyverno-version: 1.14.0
    kyverno.io/kubernetes-version: "1.30+"
    policies.kyverno.io/description: >-
      Containers must be required to run as non-root users. This policy ensures
      `runAsUser` is either unset or set to a number greater than zero.
spec:
  validationActions:
     - Audit
  evaluation:
    background:
      enabled: true
  matchConstraints:
    resourceRules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods"]
  validations:
            - expression: >-
                !has(object.spec.securityContext) ||
                !has(object.spec.securityContext.runAsUser) ||
                object.spec.securityContext.runAsUser > 0
              message: >-
                Running as root is not allowed. The field spec.securityContext.runAsUser must be unset or
                set to a number greater than zero.

            - expression: >-
                object.spec.containers.all(container, !has(container.securityContext) ||
                !has(container.securityContext.runAsUser) ||
                container.securityContext.runAsUser > 0)
              message: >-
                Running as root is not allowed. The field spec.containers[*].securityContext.runAsUser must be unset or
                set to a number greater than zero

            - expression: >-
                !has(object.spec.initContainers) ||
                object.spec.initContainers.all(container, !has(container.securityContext) ||
                !has(container.securityContext.runAsUser) ||
                container.securityContext.runAsUser > 0)
              message: >-
                Running as root is not allowed. The field spec.initContainers[*].securityContext.runAsUser must be unset or
                set to a number greater than zero

            - expression: >-
                !has(object.spec.ephemeralContainers) ||
                object.spec.ephemeralContainers.all(container, !has(container.securityContext) ||
                !has(container.securityContext.runAsUser) ||
                container.securityContext.runAsUser > 0)
              message: >-
                Running as root is not allowed. The field spec.ephemeralContainers[*].securityContext.runAsUser must be unset or
                set to a number greater than zero
