apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: limit-hostpath-type-pv
status:
  conditionStatus:
    conditions:
    - reason: Succeeded
      type: WebhookConfigured
      status: "True"
    - reason: Succeeded
      type: RBACPermissionsGranted
      status: "True"


