apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: disallow-capabilities-strict
  annotations:
    pod-policies.kyverno.io/autogen-controllers: deployments,cronjobs  
    policies.kyverno.io/title: Disallow Capabilities (Strict) in ValidatingPolicy
    policies.kyverno.io/category: Pod Security Standards (Restricted) in ValidatingPolicy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.14.0
    kyverno.io/kyverno-version: 1.14.0
    kyverno.io/kubernetes-version: "1.30+"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Adding capabilities other than `NET_BIND_SERVICE` is disallowed. In addition,
      all containers must explicitly drop `ALL` capabilities.
spec:
  validationActions:
     - Audit
  evaluation:
    background:
      enabled: true
  matchConstraints:
    resourceRules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods"]
  validations:
    # A container must either drop ALL capabilities or only add NET_BIND_SERVICE
  - expression: >-
          object.spec.containers.all(container, 
            has(container.securityContext) &&
            has(container.securityContext.capabilities) &&
            has(container.securityContext.capabilities.drop) &&
            container.securityContext.capabilities.drop.exists_one(capability, capability == 'ALL')
          ) &&
          object.spec.containers.all(container, 
            !has(container.securityContext.capabilities.add) ||
            (size(container.securityContext.capabilities.add) == 1 && container.securityContext.capabilities.add[0] == 'NET_BIND_SERVICE')
          ) &&
          (!has(object.spec.initContainers) || 
            object.spec.initContainers.all(container, 
              has(container.securityContext) &&
              has(container.securityContext.capabilities) &&
              has(container.securityContext.capabilities.drop) &&
              container.securityContext.capabilities.drop.exists_one(capability, capability == 'ALL')
            ) &&
            object.spec.initContainers.all(container, 
              !has(container.securityContext.capabilities.add) ||
              (size(container.securityContext.capabilities.add) == 1 && container.securityContext.capabilities.add[0] == 'NET_BIND_SERVICE')
            )
          ) &&
          (!has(object.spec.ephemeralContainers) || 
            object.spec.ephemeralContainers.all(container, 
              has(container.securityContext) &&
              has(container.securityContext.capabilities) &&
              has(container.securityContext.capabilities.drop) &&
              container.securityContext.capabilities.drop.exists_one(capability, capability == 'ALL')
            ) &&
            object.spec.ephemeralContainers.all(container, 
              !has(container.securityContext.capabilities.add) ||
              (size(container.securityContext.capabilities.add) == 1 && container.securityContext.capabilities.add[0] == 'NET_BIND_SERVICE')
            )
          )
 

    message: >-
        Pods must drop 'ALL' capabilities if 'drop' is set and can only add 'NET_BIND_SERVICE'.
