# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: require-probes
spec:
  steps:
  - name: create policy
    use:
      template: ../../../_step-templates/create-policy.yaml
      with:
        bindings:
        - name: file
          value: ../require-probes.yaml
  - name: wait-validating-policy-ready
    use:
      template: ../../../_step-templates/validating-policy-v1-ready.yaml
      with:
        bindings:
        - name: name
          value: require-pod-probes
  - name: step-02
    try:
    - apply:
        file: good-pods.yaml
    - apply:
        file: good-podcontrollers.yaml
    - apply:
        expect:
        - check:
            ($error != null): true
        file: bad-pod-nothing.yaml
    - apply:
        expect:
        - check:
            ($error != null): true
        file: bad-pod-notall.yaml
    - apply:
        expect:
        - check:
            ($error != null): true
        file: bad-podcontrollers.yaml

