apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: require-run-as-nonroot
  annotations:
    policies.kyverno.io/title: Require runAsNonRoot in ValidatingPolicy
    policies.kyverno.io/category: Pod Security Standards (Restricted) in ValidatingPolicy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.14.0
    kyverno.io/kyverno-version: 1.14.0
    kyverno.io/kubernetes-version: "1.30+"
    policies.kyverno.io/description: >-
      Containers must be required to run as non-root. This policy ensures
      `runAsNonRoot` is set to true.
spec:
  validationActions:
     - Audit
  evaluation:
    background:
      enabled: true
  matchConstraints:
    resourceRules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods"]
  variables:
  - name: allContainers
    expression: >-
      object.spec.containers + 
      (has(object.spec.initContainers) ? object.spec.initContainers : []) + 
      (has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : [])

  validations:
  - expression: >-
      (
        (has(object.spec.securityContext) &&
         has(object.spec.securityContext.runAsNonRoot) &&
         object.spec.securityContext.runAsNonRoot == true) &&
        variables.allContainers.all(container, 
          !has(container.securityContext) || 
          !has(container.securityContext.runAsNonRoot) || 
          container.securityContext.runAsNonRoot == true)
      ) || 
      variables.allContainers.all(container, 
        has(container.securityContext) && 
        has(container.securityContext.runAsNonRoot) && 
        container.securityContext.runAsNonRoot == true)
    message: >-
      Running as root is not allowed. Either spec.securityContext.runAsNonRoot 
      must be set to true, or all containers (spec.containers[*], spec.initContainers[*], 
      spec.ephemeralContainers[*]) must have securityContext.runAsNonRoot set to true.
