apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: require-run-as-nonroot
status:
  conditions:
    - reason: Succeeded
      type: WebhookConfigured
      status: "True"
    - reason: Succeeded
      type: RBACPermissionsGranted
      status: "True"

