apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: disallow-host-ports-range
status:
  conditions:
    - reason: Succeeded
      type: WebhookConfigured
      status: "True"
    - reason: Succeeded
      type: RBACPermissionsGranted
      status: "True"

